### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by Greg-21**
As in the title, in this pull request I updated the Polish translation. Now it includes the additions and changes from commit b744a1c2500cf60734f1ee96bab21c45392eec50 and later.

Also, if you still support 1.15, I can create another PR with as many changes from here as possible.

### CODE REVIEW

**Comment by henkelmax** [comment]
Thank you!


> Also, if you still support 1.15, I can create another PR with as many changes from here as possible.

Would be nice!

**Comment by Greg-21** [comment]
Thank you for letting me know.

**Comment by Greg-21** [comment]
Could you please update the "Credits" section on your website? I wouldn't mind if it didn't exist at all (to me, the GitHub commit history is enough), but since it does, I wouldn't like to see thanks going to someone who is no longer the author.

**Comment by henkelmax** [comment]
https://dev.modrepo.de/minecraft/corpse/credits

It is already updated in the dev branch.

**Comment by Greg-21** [comment]
Thank you then.

**Pull request merged**
